# dropbox
# Autogenerated from man page /usr/share/man/man1/dropbox.1.gz
complete -c dropbox -s i -l install -d 'dropbox lansync [y/n]'
complete -c dropbox -s l -l list
complete -c dropbox -s a -l all -d 'Aliases: stat'

