# gnome-pomodoro
# Autogenerated from man page /usr/share/man/man1/gnome-pomodoro.1.gz
complete -c gnome-pomodoro -l preferences -d 'Open preferences window'
complete -c gnome-pomodoro -l no-default-window -d 'Run as background service'

